### ISSUE TITLE
Save upon onBeforeUnload

### ISSUE THREAD

**Issue by dannybloe** [michaelcontento/redux-storage-decorator-debounce#23]
Hiya folks, 

Good work with the debouncer. One request: can you do a flush/save in the onBeforeUnload event? That's the moment where at the moment you will loose data if you close the window within the debounce interval.

Cheers

**Comment by dannybloe** [comment]
I just noticed that you only want to do that if there is a save pending in the timeout queue. Otherwise you cannot ever clear the local storage manually because upon reload it restores the just deleted local storage in the beforeunload handler.

**Comment by michaelcontento** [comment]
Hi, would it be possible for you to test PR #25?

**Comment by alebiavati** [comment]
Hi, I think this pull request brought in a bug: the clearTimeout doesn't actually set the `lastTimeout` variable to null, therefore `save()` is always called on `beforeunload`, even if the lastTimeout was cleared. And because the `lastState` is null, it erases the localStorage altogether.

I can send a quick pull request to fix this.

**Comment by caiobalthazar** [comment]
I had the same issue of having my storage erased on unload/reload :(
I would suggest merging the fix asap.
